### ISSUE TITLE
How to generate multisig transactions

### ISSUE THREAD

**Issue by lezhnev74** [evias/nem-php#5]
Hi! 
Can you show usage example on how to convert account into a multisig account?

Thanks!

**Comment by evias** [comment]
Hello,

This is not yet supported in this SDK. I have just changed the structure of the package in order to be less laravel oriented and also introduced a new model abstraction.

Unfortunately the NIS requests specialization is not finished yet. So the only way to do this with this package is as follows (using the integrated API wrapper) :

```
$nemAPI = new NEM\API();
$nemAPI->setOptions([
    "protocol" => "http",
    "use_ssl" => false,
    "host" 	  => "go.nem.ninja",
    "port"    => 7890,
    "endpoint" => "/",
]);

$data = [
    "transaction" => [
        "" => ""
    ],
    "privateKey" => "xxx"
];

$api->postJSON("", json_encode($data));
```

referring to https://nemproject.github.io/#converting-an-account-to-a-multisig-account for the content of the transaction.

Currently this nem-php package is undergoing a revamp and sadly the SDK features cannot be used before I have created the correct unit testing suite. Please have a look at the `tests/` folder to view which classes are safe to use in the package.

Thank you for understanding :)

**Comment by evias** [comment]
You can also of course have a look at the SDK model abstraction under `src/Models/Transaction` and `src/Models/Transactions/X`

it is not unit tested but the base features might be fine already. I would not run a production over this *before all unit tests are done* if I were you. :)

**Comment by evias** [comment]
@lezhnev74, I have gotten some help from @CS76 on a first Service implementation, please have a look here for an Idea on how *specialised NIS API requests* are to be defined in the library:

https://github.com/evias/nem-php/blob/master/src/Infrastructure/Account.php

The transaction business is the next step for this package. You may get an update in the next few days.
